name: media_nest
description: Flutter app for personal media archiving, offline playback, and source management powered by an on-device Rust server.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  ffmpeg_kit_flutter_new_min: ^3.1.0
  http: ^1.2.0
  path_provider: ^2.1.5
  video_player: ^2.9.2
  flutter_vlc_player: 7.4.3
  share_plus: ^12.0.1
  photo_manager: ^3.9.0
  sensors_plus: ^4.0.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
